import { ProductType } from "@/components/ProductDetailModal";

export const sembakoProducts: ProductType[] = [
  // Beras
  {
    id: "beras-1",
    name: "Beras Premium Cap Bunga 5kg",
    price: 72000,
    originalPrice: 78000,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=500",
    category: "Beras",
    unit: "Karung",
    discount: "8%",
    description: "Beras premium kualitas terbaik, pulen dan wangi. Cocok untuk kebutuhan rumah tangga dan warung makan.",
  },
  {
    id: "beras-2",
    name: "Beras Pandan Wangi 10kg",
    price: 145000,
    image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&q=80&w=500",
    category: "Beras",
    unit: "Karung",
    isNew: true,
    description: "Beras pandan wangi asli dengan aroma khas yang menggugah selera.",
  },
  {
    id: "beras-3",
    name: "Beras Rojolele 25kg",
    price: 320000,
    originalPrice: 350000,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=500",
    category: "Beras",
    unit: "Karung",
    discount: "9%",
    description: "Beras rojolele premium dalam kemasan grosir, cocok untuk warung dan rumah makan.",
  },
  // Gula
  {
    id: "gula-1",
    name: "Gulaku Gula Pasir Putih 1kg",
    price: 16500,
    originalPrice: 18000,
    image: "https://images.unsplash.com/photo-1581447100595-3a813597427a?auto=format&fit=crop&q=80&w=500",
    category: "Gula",
    unit: "Pack",
    discount: "8%",
    description: "Gula pasir putih berkualitas tinggi, higienis dan bersih untuk segala keperluan masak.",
  },
  {
    id: "gula-2",
    name: "Gula Merah Jawa 500g",
    price: 12000,
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&q=80&w=500",
    category: "Gula",
    unit: "Pack",
    description: "Gula merah asli Jawa, manis alami untuk minuman dan masakan tradisional.",
  },
  {
    id: "gula-3",
    name: "Gula Pasir Lokal 1kg",
    price: 14500,
    image: "https://images.unsplash.com/photo-1581447100595-3a813597427a?auto=format&fit=crop&q=80&w=500",
    category: "Gula",
    unit: "Pack",
    isNew: true,
    description: "Gula pasir lokal berkualitas dengan harga ekonomis.",
  },
  // Minyak Goreng
  {
    id: "minyak-1",
    name: "Bimoli Minyak Goreng 2 Liter",
    price: 34500,
    originalPrice: 38900,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=500",
    category: "Minyak Goreng",
    unit: "Botol",
    discount: "11%",
    description: "Minyak goreng berkualitas dengan kandungan vitamin E untuk hasil gorengan yang renyah.",
  },
  {
    id: "minyak-2",
    name: "Sania Minyak Goreng Refill 2L",
    price: 32000,
    image: "https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?auto=format&fit=crop&q=80&w=500",
    category: "Minyak Goreng",
    unit: "Pouch",
    isNew: true,
    description: "Minyak goreng kemasan refill hemat, cocok untuk kebutuhan sehari-hari.",
  },
  {
    id: "minyak-3",
    name: "Tropical Minyak Goreng 5L",
    price: 78000,
    originalPrice: 85000,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=500",
    category: "Minyak Goreng",
    unit: "Jerigen",
    discount: "8%",
    description: "Minyak goreng kemasan besar untuk kebutuhan warung dan usaha kuliner.",
  },
  // Daging
  {
    id: "daging-1",
    name: "Daging Sapi Has Dalam 500g",
    price: 85000,
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&q=80&w=500",
    category: "Daging",
    unit: "Pack",
    description: "Daging sapi segar pilihan, cocok untuk steak, rendang, atau masakan berkuah.",
  },
  {
    id: "daging-2",
    name: "Ayam Potong Karkas 1kg",
    price: 38000,
    originalPrice: 42000,
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&q=80&w=500",
    category: "Daging",
    unit: "Ekor",
    discount: "10%",
    description: "Ayam potong segar berkualitas, siap olah untuk berbagai masakan.",
  },
  {
    id: "daging-3",
    name: "Daging Sapi Giling 500g",
    price: 75000,
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&q=80&w=500",
    category: "Daging",
    unit: "Pack",
    isNew: true,
    description: "Daging sapi giling segar untuk bakso, burger, atau tumisan.",
  },
  // Telur
  {
    id: "telur-1",
    name: "Telur Ayam Negeri 1kg (±16 butir)",
    price: 28000,
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&q=80&w=500",
    category: "Telur",
    unit: "Kg",
    description: "Telur ayam negeri segar dengan ukuran seragam, kaya protein.",
  },
  {
    id: "telur-2",
    name: "Telur Bebek Asin 6 butir",
    price: 24000,
    image: "https://images.unsplash.com/photo-1498654077810-12c21d4d6dc3?auto=format&fit=crop&q=80&w=500",
    category: "Telur",
    unit: "Pack",
    isNew: true,
    description: "Telur bebek asin khas dengan rasa gurih dan kuning telur masir.",
  },
  {
    id: "telur-3",
    name: "Telur Ayam Kampung 10 butir",
    price: 35000,
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&q=80&w=500",
    category: "Telur",
    unit: "Pack",
    description: "Telur ayam kampung organik, lebih bergizi dan lezat.",
  },
  // Susu
  {
    id: "susu-1",
    name: "Frisian Flag SKM Putih 370g",
    price: 12500,
    image: "https://images.unsplash.com/photo-1550583724-12558142ab12?auto=format&fit=crop&q=80&w=500",
    category: "Susu",
    unit: "Kaleng",
    description: "Susu kental manis berkualitas untuk minuman dan bahan masakan.",
  },
  {
    id: "susu-2",
    name: "Indomilk UHT Full Cream 1L",
    price: 18500,
    originalPrice: 20000,
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&q=80&w=500",
    category: "Susu",
    unit: "Kotak",
    discount: "8%",
    description: "Susu UHT full cream dengan kandungan gizi lengkap untuk seluruh keluarga.",
  },
  {
    id: "susu-3",
    name: "Dancow Fortigro 800g",
    price: 62000,
    image: "https://images.unsplash.com/photo-1550583724-12558142ab12?auto=format&fit=crop&q=80&w=500",
    category: "Susu",
    unit: "Box",
    isNew: true,
    description: "Susu bubuk pertumbuhan untuk anak dengan nutrisi lengkap.",
  },
  // Garam & Bumbu
  {
    id: "bumbu-1",
    name: "Garam Cap Kapal 500g",
    price: 5500,
    image: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&q=80&w=500",
    category: "Garam & Bumbu",
    unit: "Pack",
    description: "Garam beryodium berkualitas untuk kebutuhan masak sehari-hari.",
  },
  {
    id: "bumbu-2",
    name: "Merica Bubuk 50g",
    price: 8500,
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=500",
    category: "Garam & Bumbu",
    unit: "Pack",
    description: "Merica bubuk halus dengan aroma kuat untuk bumbu masakan.",
  },
  {
    id: "bumbu-3",
    name: "Bawang Putih 250g",
    price: 15000,
    image: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&q=80&w=500",
    category: "Garam & Bumbu",
    unit: "Pack",
    isNew: true,
    description: "Bawang putih segar pilihan untuk bumbu dasar masakan.",
  },
  // Ikan
  {
    id: "ikan-1",
    name: "Ikan Tongkol Segar 1kg",
    price: 35000,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=500",
    category: "Ikan",
    unit: "Kg",
    description: "Ikan tongkol segar tangkapan nelayan lokal, kaya omega-3.",
  },
  {
    id: "ikan-2",
    name: "Ikan Teri Medan Kering 250g",
    price: 45000,
    originalPrice: 50000,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=500",
    category: "Ikan",
    unit: "Pack",
    discount: "10%",
    description: "Ikan teri Medan kering berkualitas untuk sambal atau lauk.",
  },
  {
    id: "ikan-3",
    name: "Ikan Lele Segar 1kg",
    price: 28000,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=500",
    category: "Ikan",
    unit: "Kg",
    isNew: true,
    description: "Ikan lele segar dari kolam budidaya lokal.",
  },
  // Sayuran
  {
    id: "sayur-1",
    name: "Kangkung Segar 1 Ikat",
    price: 5000,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=500",
    category: "Sayuran",
    unit: "Ikat",
    description: "Kangkung segar pilihan, cocok untuk tumis atau plecing.",
  },
  {
    id: "sayur-2",
    name: "Wortel Segar 500g",
    price: 8000,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=500",
    category: "Sayuran",
    unit: "Pack",
    isNew: true,
    description: "Wortel segar berkualitas, kaya vitamin A untuk kesehatan mata.",
  },
  {
    id: "sayur-3",
    name: "Bayam Segar 1 Ikat",
    price: 4000,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=500",
    category: "Sayuran",
    unit: "Ikat",
    description: "Bayam segar untuk sayur bening atau tumisan.",
  },
];

export const categorySlugMap: Record<string, string> = {
  "beras": "Beras",
  "gula": "Gula",
  "minyak-goreng": "Minyak Goreng",
  "daging": "Daging",
  "telur": "Telur",
  "susu": "Susu",
  "garam-bumbu": "Garam & Bumbu",
  "ikan": "Ikan",
  "sayuran": "Sayuran",
};

export const categoryInfo: Record<string, { name: string; slug: string; desc: string }> = {
  "Beras": { name: "Beras", slug: "beras", desc: "Berbagai jenis beras berkualitas" },
  "Gula": { name: "Gula", slug: "gula", desc: "Gula pasir & gula merah" },
  "Minyak Goreng": { name: "Minyak Goreng", slug: "minyak-goreng", desc: "Minyak goreng & kelapa" },
  "Daging": { name: "Daging", slug: "daging", desc: "Daging sapi & ayam segar" },
  "Telur": { name: "Telur", slug: "telur", desc: "Telur ayam & bebek" },
  "Susu": { name: "Susu", slug: "susu", desc: "Susu & olahan susu" },
  "Garam & Bumbu": { name: "Garam & Bumbu", slug: "garam-bumbu", desc: "Garam, merica, bumbu dapur" },
  "Ikan": { name: "Ikan", slug: "ikan", desc: "Ikan segar & olahan" },
  "Sayuran": { name: "Sayuran", slug: "sayuran", desc: "Sayuran segar pilihan" },
};

export function getProductsByCategory(category: string): ProductType[] {
  return sembakoProducts.filter(p => p.category === category);
}

export function getRandomProducts(count: number): ProductType[] {
  const shuffled = [...sembakoProducts].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
